[package]
name = "pisugar-core"
version = "0.1.0"
authors = ["PiSugare"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
rppal = "0.11.3"