name: build-other

on:
  workflow_call:

jobs:
  build-other:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fix cargo config
        run: sed -e "s/.*replace-with.*//g" -i .cargo/config.toml

      - name: Download all
        uses: actions/download-artifact@v3
        with:
          path: |
            download

      - name: Move files
        run: |
          set -x
          mkdir -p electron/dist
          mv -f download/pisugar-web/* electron/dist/
          rm -rf download/pisugar-web
          mkdir -p target
          for i in $(ls download); do
            rsync -r download/$i/* target/
          done

      - run: ls -r target

      # aur for archlinux
      - run: (cd scripts/aur; sh build-aur.sh)

      # Linux module
      - run: tar -czvf pisugar-module.tar.gz pisugar-module

      # Upload artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pisugar-all
          path: |
            target/**/*.deb
            target/**/*.rpm
            !target/**/*src*.rpm
            scripts/*.sh
            scripts/aur/*.tar.gz
            !scripts/update-version.sh
            pisugar-module.tar.gz
          if-no-files-found: warn
